# Import Library

In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from ydata_profiling import ProfileReport

# Import Dataset

In [32]:
# Path to training and prediction dataset
train_PATH = 'D:\DAC-2023\Dataset\DataTrain_Preliminary.csv'
pred_PATH = 'D:\DAC-2023\Dataset\Data_Prediction.csv'

In [33]:
# Load training data 
df = pd.read_csv(train_PATH, delimiter=';')
df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
0,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.01,0.94,0.95,0,0.95,1,0,0,nmap
1,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
2,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
3,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
4,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112441,0,tcp,http,REJ,0,0,0,0,0,0,...,255,1.00,0.00,0.14,*,0.00,0,*,*,normal
112442,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
112443,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
112444,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
112445,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

# Duplicate Data Investigation

In [34]:
ProfileReport(df).get_duplicates()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

In [ ]:
df.drop_duplicates(inplace=True)
df

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
0,0,tcp,private,SH,0,0,0,0,0,0,...,1,0.01,0.94,0.95,0,0.95,1,0,0,nmap
1,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
2,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
3,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
4,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112440,5,tcp,smtp,SF,1377,328,0,0,0,0,...,117,0.66,0.03,0.01,0,0.00,0,0,0,normal
112442,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
112443,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
112444,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
112445,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

# Unique Value Investigation

In [ ]:
# Initialize a dictionary to store missing value representations
missing_value_representations = ['', ' ', '-', 'NA', 'N/A', '999', '-999', None, np.nan, '*', '9999', '-9999', '99999', '-99999']

# Initialize a set to store unique types of missing values
unique_missing_value_types = set()

# Iterate through columns and check for missing value representations
for column in df.columns:
    for value in df[column]:
        if value in missing_value_representations:
            unique_missing_value_types.add(value)

# Boolean indexing to filter rows with unique missing value types
filtered_df = df[df.apply(lambda row: any(val in unique_missing_value_types for val in row), axis=1)]

# Display the filtered DataFrame
print("Unique types of missing values found in the DataFrame:")
print(unique_missing_value_types)
print("Rows containing unique missing value types:")
filtered_df

Unique types of missing values found in the DataFrame:
{nan, '99999', '*', '999'}
Rows containing unique missing value types:

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
1,0,tcp,private,S0,0,0,0,0,0,0,...,5,0.02,0.08,0.00,0,1.00,1,0,0,neptune
2,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.00,0,0,0,normal
3,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.00,0,0,0,normal
4,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.00,0,0,0,normal
5,0,tcp,discard,S0,0,0,0,0,0,0,...,18,0.07,0.05,0.00,0,1.00,1,0,0,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112441,0,tcp,http,REJ,0,0,0,0,0,0,...,255,1.00,0.00,0.14,*,0.00,0,*,*,normal
112442,0,tcp,http,SF,309,758,0,0,0,0,...,255,1.00,0.00,0.02,*,0.02,*,0,0,normal
112443,0,tcp,http,SF,363,721,0,0,0,0,...,255,1.00,0.00,0.00,0,0.00,0,0,0,normal
112444,0,tcp,discard,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0,0.00,0,1,1,neptune
112445,0,tcp,http,SF,233,2538,0,0,0,0,...,255,1.00,0.00,0.02,*,0.00,0,0,0,normal

# Investigate Unique Value Based on Type of Attack

In [ ]:
# Identifying and listing the unique attack types present in the column
attack_type = df['type_of_attack'].unique()
print(f"Value contain in type_of_attack column:\n{attack_type}")

Value contain in type_of_attack column:
['nmap' 'neptune' 'normal' 'Denial of Service Attack' 'portsweep' 'satan'
 'ipsweep' 'smurf']

In [ ]:
# Exploring the distribution of these attack types to understand their prevalence in the dataset.
attack_type_counts = df['type_of_attack'].value_counts()
attack_type_counts

type_of_attack
normal                      60169
neptune                     36832
ipsweep                      3036
satan                        2905
portsweep                    2651
smurf                        2378
Denial of Service Attack     1746
nmap                         1322
Name: count, dtype: int64

In [ ]:
# Exploring the distribution of these attack types to understand their prevalence in the dataset.
attack_type_counts = df['type_of_attack'].value_counts()
total_samples = len(df)
attack_type_percentages = (attack_type_counts / total_samples) * 100

# Round the percentages to two decimal places
attack_type_percentages = attack_type_percentages.round(2)

# Print the percentages 
print(attack_type_percentages.astype(str) + '%')

type_of_attack
normal                      54.19%
neptune                     33.17%
ipsweep                      2.73%
satan                        2.62%
portsweep                    2.39%
smurf                        2.14%
Denial of Service Attack     1.57%
nmap                         1.19%
Name: count, dtype: object

In [ ]:
# Function to filter df based on type of attack
def filtered_by_type_of_attack(df, values):
    filtered = df[df['type_of_attack'] == values]
    return filtered

## Normal

In [ ]:
normal = filtered_by_type_of_attack(df, 'normal')
normal.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,type_of_attack
2,0,tcp,http,SF,285,3623,0,0,0,0,...,228,1.00,0.00,0.01,*,0.0,0,0,0,normal
3,0,tcp,http,SF,232,584,0,0,0,0,...,255,1.00,0.00,0.17,*,0.0,0,0,0,normal
4,1,tcp,smtp,SF,1080,327,0,0,0,0,...,154,0.58,0.02,0.00,*,0.0,0,0,0,normal
6,0,udp,domain_u,SF,43,43,0,0,0,0,...,254,1.00,0.01,0.01,0,0.0,0,0,0,normal
8,0,tcp,http,SF,284,614,0,0,0,0,...,255,1.00,0.00,0.10,*,0.0,0,0,0,normal

### Bool Data Type

In [ ]:
value_counts = normal['land'].value_counts()
print(value_counts)

land
0        59937
99999      144
*           81
1            7
Name: count, dtype: int64

In [ ]:
# Determine a probability threshold based on the existing distribution
# In this example, we'll use the probability of 0 as the threshold
probability_of_0 = value_counts.get(0, 0) / len(normal)

# Convert '*' and '99999' values based on the threshold
def convert_value(value):
    if value == '*':
        return 0 if np.random.rand() <= probability_of_0 else 1
    elif value == '99999':
        return 0 if np.random.rand() <= probability_of_0 else 1
    else:
        return int(value)

# Apply the conversion function to the 'land' column
normal['land'] = normal['land'].apply(convert_value)

In [ ]:
value_counts = normal['land'].value_counts()
print(value_counts)

land
0        59937
99999      144
*           81
1            7
Name: count, dtype: int64